global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'shopping-cart-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:50051']

  - job_name: 'order-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:50052']

  - job_name: 'payment-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:50053']